### ISSUE TITLE
安装完毕后HelloWorld少写了import $ from 'jquery'

### ISSUE THREAD

**Issue by choukin** [theJian/build-a-hn-front-page#3]
接下来测试一下开发环境是否搭建完成.

打开 app.js, 修改内容为:

// app.js

import React from 'react';
import { render } from 'react-dom';

class HelloWorld extends React.Component {
  render() {
    return (
        <div>Hello World</div>
        );
  }
}

render(<HelloWorld />, $('#content')[0]);

少写了import $ from 'jquery'

**Comment by theJian** [comment]
Thx! Awesome catch! :+1:

**Comment by theJian** [comment]
https://github.com/theJian/build-a-hn-front-page/commit/a7ac074f9f2ad3056533a7b8f0a7de5c584144ec
