### ISSUE TITLE
NewsItem大类下面有一处代码好像有问题

### ISSUE THREAD

**Issue by zengkan0703** [theJian/build-a-hn-front-page#6]
[**NewsItem**](https://github.com/theJian/build-a-hn-front-page#newsitem)中第2项NewsItem 来源地址最后去掉了testdata里面的url之后，重新打包看到网页中没有出现来源地址，我修改下面这两部分代码之后可以了。
这是原文中的代码
![qq 20160911155046](https://cloud.githubusercontent.com/assets/20679471/18415965/91df15b4-7837-11e6-9a48-7c93c0ee51d0.png)
![qq 20160911155206](https://cloud.githubusercontent.com/assets/20679471/18415973/b7e4dd48-7837-11e6-93ce-13e718e5a894.png)
最终的页面上并没有出现第一个代码块写的那个span标签，我觉得是因为｛｝包含的代码会被解析成js代码，并不会展示出来，然后我把｛this.props.item.url && ｝删除了，只留下了后面的span标签。
再次运行之后，报错，我查看了以下报错原因是在上面的第二张图片中，因为我们已经删除了testdata里面的url，所以URL.parse(undefined)就会报错，我就修改代码成为
![333333333305](https://cloud.githubusercontent.com/assets/20679471/18415995/9902d6ae-7838-11e6-81de-46e3e62ab271.png)
重新打包运行之后正确显示了来源地址。
不知道是不是这块儿代码确实有问题，还是我理解有误。
**（我也是刚刚开始学，有不对的地方请指出，谢谢）**

**Comment by theJian** [comment]
不好意思, 这里是文中没有叙述清楚.
这不是 Bug, 是个 Feature. 没有显示 span 是对的, 对于没有 url 的项目, 不显示来源地址, 你可以看看 [Hacker News](https://news.ycombinator.com/news) 的页面, 只有具有 url 的项目才显示来源地址.
这里文中没有交代清楚, 你有兴趣发个 PR 来吗?

**Comment by zengkan0703** [comment]
不好意思，我换回文章中代码试了一下，效果也是一样的。不过在所有代码中引用getDomain()方法的只有getTitle里面，但是又是在｛｝里面引用的，为什么最终那个span能显示出来。
我觉得可能是我对react中｛｝本身理解不对，而且也没看懂｛｝里面代码什么意思，麻烦您可以的话点拨一下，谢谢啦。

**Comment by theJian** [comment]
`{ }` 中的意思是 只有当 this.props.item.url  存在的时候, 才返回 span 显示出来, 当 this.props.item.url 存在时, 这个表达式会返回 span, 否则, 返回 this.props.item.url, 这应该是个 undefined. 如果你了解 `&&` 的特性的话, 这个应该不难理解. 我想这段写是不是太快了, 对新手不太友好.

**Comment by zengkan0703** [comment]
我复习了一下语句中&&的用法，这段代码看懂了，你的代码确实没问题，之前没理解对，谢谢解答。

最后非常感谢这个教程啊，做完之后感觉对react和webpack有基本的了解了，也顺带了解了一下es6的一些新语法。

再次谢谢 theJian老师。
